name: Deploy Github Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn lint
